export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const AUTHORIZE_USER = "AUTHORIZE_USER";
export const DONT_AUTHORIZE_USER = "DONT_AUTHORIZE_USER";
export const CLEAR_CART = "CLEAR_CART";